Repository CSC207-2022F-UofT/course-project-fitpredict, pull requests merged in 2022-11, with the labels that each got.

#13 [user-login] UserLogin system and its corresponding screen are completed.
  .idea/.gitignore
  .idea/misc.xml
  accounts.ser
  gradlew.bat
  src/main/java/user_login/CurrentUser.java
  src/main/java/user_login/LabelTextPanel.java
  src/main/java/user_login/LoginInputBoundary.java
  src/main/java/user_login/LoginScreenMain.java
  src/main/java/user_login/ReadWriter.java
  src/main/java/user_login/User.java
  src/main/java/user_login/UserAccountList.java
  src/main/java/user_login/UserLogin.java
  src/main/java/user_login/UserLoginController.java
  src/main/java/user_login/UserLoginScreen.java
  src/main/java/user_login/UserReadWriter.java
Labels: enhancement

#17 [data-predict] Predictor, CaloriePredictor, PredictManager, BMIPredictor, WeightPredictor completed
  .gitignore
  src/main/java/predictor/BMIPredictor.java
  src/main/java/predictor/CaloriePredictor.java
  src/main/java/predictor/PredictManager.java
  src/main/java/predictor/Predictor.java
  src/main/java/predictor/WeightPredictor.java
  src/test/java/predictor/BMIPredictorTest.java
  src/test/java/predictor/CaloriePredictorTest.java
  src/test/java/predictor/PredictManagerTest.java
  src/test/java/predictor/WeightPredictorTest.java
Labels: enhancement

#15 [display-zoom] DataPoint, DataPointMap, DataPointManager completed
  src/main/java/DisplayZoom/DataPoint.java
  src/main/java/DisplayZoom/DataPointManager.java
  src/main/java/DisplayZoom/DataPointMap.java
  src/test/java/DisplayZoom/DataPointManagerTest.java
  src/test/java/DisplayZoom/DataPointMapTest.java
  src/test/java/DisplayZoom/DataPointTest.java
Labels: enhancement

#14 [user-creation] UserCreator system and the corresponding screen are completed.
  .idea/vcs.xml
  RegisteredAccountsList.ser
  gradlew.bat
  src/main/java/user_creator/CreationInputBoundary.java
  src/main/java/user_creator/LabelTextPanel.java
  src/main/java/user_creator/ReadWriter.java
  src/main/java/user_creator/User.java
  src/main/java/user_creator/UserAccountList.java
  src/main/java/user_creator/UserCreationController.java
  src/main/java/user_creator/UserCreationScreen.java
  src/main/java/user_creator/UserCreationScreenMain.java
  src/main/java/user_creator/UserCreator.java
  src/main/java/user_creator/UserReadWriter.java
Labels: enhancement

#19 [display-view] Dashboard, DashboardScreen, Table implemented
  .idea/.gitignore
  .idea/misc.xml
  .idea/vcs.xml
  gradlew
  gradlew.bat
  src/main/java/DisplayView/Dashboard.java
  src/main/java/DisplayView/DashboardScreen.java
  src/main/java/DisplayView/Graph.java
  src/main/java/DisplayView/LineGraph.java
  src/main/java/DisplayView/ScatterGraph.java
  src/main/java/DisplayView/Table.java
  src/main/java/DisplayView/VisualUnit.java
  src/main/java/Main.java
Labels: enhancement

#27 [refactor-current-user-add-function] User.getDataPointMap() implemented
  src/main/java/entities/CurrentUser.java
  src/main/java/entities/User.java
  src/main/java/screens/DashboardScreen.java
Labels: enhancement

#23 [exercise-manager-user-class-integration] ExerciseCreationController and ExerciseCreationInteractor are completeed
  .idea/vcs.xml
  src/main/java/entities/Exercise.java
  src/main/java/screens/ExerciseCreationMain.java
  src/main/java/screens/ExerciseCreationScreen.java
  src/main/java/screens/LoginScreenMain.java
  src/main/java/screens/ResultScreen.java
  src/main/java/use_cases/ExerciseCreationInteractor.java
  src/main/java/use_cases/ExerciseInputBoundary.java
  src/main/java/use_cases/ExerciseMap.java
  src/test/java/exercise/ExerciseCreationInteractorTest.java
  src/test/java/exercise/ExerciseManagerTest.java
  src/test/java/exercise/ExerciseMapTest.java
  src/test/java/exercise/ExerciseTest.java
Labels: documentation, enhancement

#39 [refactor-fix-datapoint] refactor to fixed bug
  src/main/java/entities/DataPoint.java
  src/main/java/use_cases/DataPointMap.java
  src/test/java/display_zoom/DataPointMapTest.java
  src/test/java/display_zoom/DataPointTest.java
Labels: bug

#43 [refactor-fix-displayview-jswing] fixed errors of relating to displayview and jswing
  .idea/misc.xml
  src/main/java/Main.java
  src/main/java/screens/DashboardScreen.java
  src/main/java/screens/Table.java
Labels: bug

#46 [refactor-data-predict-fix-and-implement-tests] Implement tests
  src/test/java/predictor/BMIPredictorTest.java
  src/test/java/predictor/CaloriePredictorTest.java
  src/test/java/predictor/WeightPredictorTest.java
Labels: enhancement

#47 [data-input-ui-improvements]
  accounts.ser
  src/main/java/screens/DataInputScreen.java
  src/main/java/screens/DataInputScreenMain.java
Labels: enhancement
