Repository CSC207-2022F-UofT/course-project-fitpredict, pull requests merged in 2022-12, with the labels that each got.

#50 [refactor-data-predict-implement-predictmanager-tests] Implement tests & Bugfixes
  src/main/java/controllers/DataInputController.java
  src/main/java/entities/CurrentUser.java
  src/main/java/screens/DashboardScreen.java
  src/main/java/screens/DataInputScreen.java
  src/main/java/use_cases/BMIPredictor.java
  src/main/java/use_cases/CaloriePredictor.java
  src/main/java/use_cases/WeightPredictor.java
  src/test/java/data_input/DataInputTest.java
  src/test/java/predictor/BMIPredictorTest.java
  src/test/java/predictor/CaloriePredictorTest.java
  src/test/java/predictor/PredictManagerTest.java
  src/test/java/predictor/WeightPredictorTest.java
  src/test/java/tutorial/HelloWorldTest.java
Labels: bug, enhancement

#51 [update-readme] README.md is updated with instructions on how to run and use program files
  README.md
  images/10input_data_screen.png
  images/11data_inputted_successfully.png
  images/1run_main.png
  images/2first_login_screen.png
  images/3create_user_screen.png
  images/4account_created_successfully.png
  images/5login_to_account_screen.png
  images/6logged_in_successfully_screen.png
  images/7main_menu_click_create_exercise.png
  images/8create_exercise_screen.png
  images/9exercise_added_screen.png
Labels: documentation

#59 [refactor-fix-currentuser-tests] fixed tests for CurrentUser
  src/test/java/UserLogin/CurrentUserTest.java
Labels: bug

#62 [integrate-screens-into-one-gui] Fixed issue with UserAccountLists not writing to accounts.ser
  RegisteredAccountsList.ser
  src/main/java/Main.java
  src/main/java/controllers/UserCreationController.java
  src/main/java/entities/User.java
  src/main/java/screens/MainMenuScreen.java
  src/main/java/screens/UserCreationScreen.java
  src/main/java/use_cases/DataPointMap.java
  src/main/java/use_cases/UserCreator.java
  src/main/java/use_cases/UserLogin.java
Labels: bug

#63 [refactor-datapoint-tests] Refactored tests for DataPoint, DataPointMap, and DataPointManager
  src/test/java/display_zoom/DataPointManagerTest.java
  src/test/java/display_zoom/DataPointMapTest.java
  src/test/java/display_zoom/DataPointTest.java
Labels: bug, enhancement

#61 60 refactor user login tests
  src/test/java/login/UserAccountListTest.java
  src/test/java/login/UserLoginTest.java
Labels: bug

#67 [refactor-display-view-fix-table] Fixed table not showing, added predictions
  src/main/java/controllers/DashboardController.java
  src/main/java/entities/DataPoint.java
  src/main/java/screens/DashboardScreen.java
  src/main/java/screens/MainMenuScreen.java
  src/main/java/use_cases/DataPointManager.java
  src/main/java/use_cases/PredictManager.java
  src/main/java/use_cases/UpdatePredictions.java
  src/test/java/predictor/PredictManagerTest.java
Labels: bug

#69 Comment exercise code and rename exercise tests
  src/main/java/screens/ExerciseCreationMain.java
  src/main/java/screens/ExerciseCreationScreen.java
  src/main/java/use_cases/ExerciseCreationInteractor.java
  src/main/java/use_cases/ExerciseMap.java
  src/test/java/data_input/DataInputTest.java
  src/test/java/exercise/ExerciseCreationInteractorTest.java
  src/test/java/exercise/ExerciseManagerTest.java
  src/test/java/exercise/ExerciseMapTest.java
  src/test/java/exercise/ExerciseTest.java
  src/test/java/login/CurrentUserTest.java
  src/test/java/login/UserLoginTest.java
  src/test/java/predictor/BMIPredictorTest.java
  src/test/java/predictor/CaloriePredictorTest.java
  src/test/java/predictor/PredictManagerTest.java
  src/test/java/predictor/WeightPredictorTest.java
  src/test/java/user_creator/UserCreatorTest.java
  src/test/java/user_creator/UserEntityTest.java
Labels: bug

#74 [refactor-datapoint-timezone] Timezone of DataPoint creation changed
  accounts.ser
  src/main/java/entities/DataPoint.java
  src/test/java/display_zoom/DataPointTest.java
Labels: bug

#80 [update-readme-for-presentation] Updated README to add a section for the TA when marking
  README.md
Labels: documentation

#83 [clean-up-comments-and-code] Clean up the comments & Code
  src/main/java/Main.java
  src/main/java/controllers/DashboardController.java
  src/main/java/controllers/DataInputController.java
  src/main/java/entities/DataPoint.java
  src/main/java/entities/User.java
  src/main/java/screens/Dashboard.java
  src/main/java/screens/DashboardScreen.java
  src/main/java/screens/DataInputScreen.java
  src/main/java/screens/Graph.java
  src/main/java/screens/LineGraph.java
  src/main/java/screens/ScatterGraph.java
  src/main/java/screens/Table.java
  src/main/java/screens/VisualUnit.java
  src/main/java/use_cases/BMIPredictor.java
  src/main/java/use_cases/PredictManager.java
  src/main/java/use_cases/Predictor.java
  src/main/java/use_cases/UpdatePredictions.java
  src/main/java/use_cases/UserLogin.java
  src/main/java/use_cases/WeightPredictor.java
Labels: documentation

#85 [update-readme-include-design-patterns] Added note about design patterns followed in README.md
  README.md
Labels: documentation
